### ISSUE TITLE
Save Panel: Download standalone viewer button send user to wrong URL.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#162]
User sent to https://tcga.ngchm.net/ZipAppDownload which eventually gets redirected to tcga.ngchm.net.

**Comment by marohrdanz** [comment]
This also occurs on the [current production system](https://www.ngchm.net/Downloads/ngChmApp.html) and a local copy of the lates release.

**Comment by ChrisWakefield** [comment]
@marohrdanz @jmelott This is unrelated to the "save-state-feature", so I will remove that label.

**Comment by ChrisWakefield** [comment]
Handled at proxy server, so we agreed to close this.
