### ISSUE TITLE
Save panel: PDF generation breaks if saved map does not have visible detail panel.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#166]
If I open an unsaved map, replace the summary pane with a 3D scatterplot, select the axes as expected on the detail map then replace the detail map with a summary map and create a pdf, the pdf creation works fine.
If I save that file, then reload it, and then try to make a pdf from the reloaded file, it fails with the error below.

NGCHM_Util.js?v=2.20.2:72 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at Object.NgChm.UTIL.setElementPositionSize (NGCHM_Util.js?v=2.20.2:72)
    at Object.NgChm.DET.setViewPort (DetailHeatMapDisplay.js?v=2.20.2:943)
    at Object.NgChm.DET.drawDetailHeatMap (DetailHeatMapDisplay.js?v=2.20.2:237)
    at drawDetailTimeout (DetailHeatMapDisplay.js?v=2.20.2:89)
NgChm.UTIL.setElementPositionSize @ NGCHM_Util.js?v=2.20.2:72
NgChm.DET.setViewPort @ DetailHeatMapDisplay.js?v=2.20.2:943
NgChm.DET.drawDetailHeatMap @ DetailHeatMapDisplay.js?v=2.20.2:237
drawDetailTimeout @ DetailHeatMapDisplay.js?v=2.20.2:89
setTimeout (async)
NgChm.DET.setDrawDetailTimeout @ DetailHeatMapDisplay.js?v=2.20.2:87
NgChm.DET.flushDrawingCache @ DetailHeatMapDisplay.js?v=2.20.2:116
NgChm.DET.processDetailMapUpdate @ DetailHeatMapDisplay.js?v=2.20.2:55
sendAll @ MatrixManager.js?v=2.20.2:1456
sendAllListeners @ MatrixManager.js?v=2.20.2:1443
sendCallBack @ MatrixManager.js?v=2.20.2:1437
setTileCacheEntry @ MatrixManager.js?v=2.20.2:1368
fr.onload @ MatrixManager.js?v=2.20.2:1497
load (async)
(anonymous) @ MatrixManager.js?v=2.20.2:1493
(anonymous) @ zip.js?v=2.20.2:577
getData @ zip.js?v=2.20.2:289
getWriterData @ zip.js?v=2.20.2:576
step @ zip.js?v=2.20.2:445
setTimeout (async)
(anonymous) @ zip.js?v=2.20.2:417
writeUint8Array @ zip.js?v=2.20.2:285
(anonymous) @ zip.js?v=2.20.2:415
reader.onload @ zip.js?v=2.20.2:180
load (async)
readUint8Array @ zip.js?v=2.20.2:179
step @ zip.js?v=2.20.2:402
launchProcess @ zip.js?v=2.20.2:449
inflate @ zip.js?v=2.20.2:462
(anonymous) @ zip.js?v=2.20.2:601
init @ zip.js?v=2.20.2:278
(anonymous) @ zip.js?v=2.20.2:597
reader.onload @ zip.js?v=2.20.2:180
load (async)
readUint8Array @ zip.js?v=2.20.2:179
Entry.getData @ zip.js?v=2.20.2:589
getTile @ MatrixManager.js?v=2.20.2:1490
setReadWindow @ MatrixManager.js?v=2.20.2:1630
setReadWindow @ MatrixManager.js?v=2.20.2:769
NgChm.PDF.callViewerHeatmapPDF @ PdfGenerator.js?v=2.20.2:169
onclick @ chm.html:185

**Comment by marohrdanz** [comment]
This was probably resolved in e4567f4

**Comment by jmelott** [comment]
Same issue, but a different error message now in version 2.21.2.
 
PdfGenerator.js:63 Uncaught TypeError: Cannot read properties of null (reading 'colLabelFont')
    at Object.NgChm.PDF.openPdfPrefs (PdfGenerator.js:63:47)
    at HTMLDivElement.onclick (chm.html:366:95)

**Comment by jmelott** [comment]
Fixed in v2.23.2 build 4.
