### ISSUE TITLE
User help message too wide after downloading .ngchm file

### ISSUE THREAD

**Issue by marohrdanz** [MD-Anderson-Bioinformatics/NG-CHM#171]
When saving a .ngchm file via: 

- click upper-right hamburger menu
- choose 'Save Heat Map Changes...'
- click 'SAVE TO .NGCHM' button
 
the second dialog regarding downloading the viewer is too wide. The user has to scroll far to the right to read the text.

Verified in both Chrome and Firefox on mac for the version deployed to ngchm.net (claims to be version 2.20.1.)

![Screen Shot 2021-10-27 at 2 36 54 PM](https://user-images.githubusercontent.com/15746330/139135043-f203defb-df5a-4c9c-96f5-fe3f383730be.png)

**Comment by marohrdanz** [comment]
Note: the reference commit message 6ad29dd included a typo referencing this issue. The commit should have referenced #170, and has since been rebased to include the proper reference.

**Comment by jmelott** [comment]
Still present 2022 02 07.
