### ISSUE TITLE
Linkouts for PubMed no longer working in Linkout pane.   Need to be modified to open in separate tab.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#175]

**Comment by ChrisWakefield** [comment]
It looks like a "Mixed content error" because the window is originally https but was requesting a frame using http.  It seems pubmed now allows (and forces) https, so no big deal to change, then it will open in the linkout panel.

**Comment by jmelott** [comment]
Still present 2022 02 07.
