### ISSUE TITLE
The covariate file contains class labels that do not match the data matrix labels

### ISSUE THREAD

**Issue by happar73** [MD-Anderson-Bioinformatics/NG-CHM#19]
Hi NG-CHM，

Thanks for developing such a convinent heatmap program.

I used this program to run my single-cell RNA data. When I uploaded the Covariate files, I always got error: 

> the covariate file contains class labels that do not match the data matrix labels. 

I have checked my data matrix and prettery sure they are matched.

Can you help me figure it out?

Many thanks!

Yale Liu

**Comment by bmbroom** [comment]
Hi Yale,

Thanks for asking.  We're happy to help.

What platform are you using to create the NG-CHM?  (R, Gui Builder, Galaxy, etc.)  If you can see the version number that would help also.

Some general tips for subtle problems could occur on some platforms if you're reading/inputting the data from a file:
- There are non-tab characters between the fields
- There are carriage-return (\r) characters at the end of lines (we're trying to fix this whenever we see it).

Bradley

**Comment by happar73** [comment]
Hi Bradley,

I am using the NG-CHM builder, I can't see the version number, but I have the link: [https://build.ngchm.net/NGCHM-web-builder/]
I finally fixed it. I have to input the covariates in the data Matrix, then creat a new  covariate table to upload as covariate bar. I separeted them at first, that's why I got error: **do not match the data matrix labels**.
The tutorial is really helpful[https://build.ngchm.net/NGCHM-web-builder/ngChmBuilderHelp.html]
The heatmap looks really cool, and NG-CHM builder is helpful for people are not good at write code.

Thanks,

Yale

**Comment by bmbroom** [comment]
I am glad you got it working.  It should be possible to upload them separately as well.  We will work on making it easier to understand why the system didn't accept them and/or make the upload process clearer.

Regards,
Bradley

**Comment by happar73** [comment]
@bmbroom It will really helpful if you can also extend the data matrix to 10,000 rows and 10,000 columns (present <3500).

Warms,
Yale

**Comment by bmbroom** [comment]
Thanks Yale.  It is on our to-do list.  The problem is that clustering time and memory requirements grow quickly and soon become too large for the server we have running the builder.  We have some long term plans to allocate additional resources dynamically to permit building larger matrices.   

Best,
Bradley
