### ISSUE TITLE
Save Panel: Many messages in console when loading saved map.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#192]
DetailHeatMapDisplay.js?v=2.20.2:1812 {m: 'mismatch during update', parentElement: null, parent: div#labelDiv2}
[m_12_3200_3200_genes_genes (8).ngchm.zip](https://github.com/MD-Anderson-Bioinformatics/NG-CHM/files/7558034/m_12_3200_3200_genes_genes.8.ngchm.zip)

**Comment by marohrdanz** [comment]
This has been resolved.
