### ISSUE TITLE
If in Vertical ribbon mode in detail map, if user scrolls over Vertical Ribbon Button, it will dehighlight.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#202]

**Comment by jmelott** [comment]
Sometimes, but not always will happen with Normal view button as well.   Never seems to happen with Horizontal View button.

**Comment by bmbroom** [comment]
It happens to me equally for all buttons.
It happens when you have >1 detail pane and are hovering over the buttons in a secondary pane and the zoom mode of the secondary pane differs from that of the primary pane.
I'll have a patch shortly (to follow the save-state-feature merge).
