### ISSUE TITLE
PDF legends not rendered properly for some maps.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#225]
Using lake-2016-single-cell ngchm, last page of pdf legends not rendered properly.
[lake-2016-single-cell (1).pdf](https://github.com/MD-Anderson-Bioinformatics/NG-CHM/files/7849290/lake-2016-single-cell.1.pdf)

**Comment by bmbroom** [comment]
In the attached file and when I run it, I see the message:
```
Column Covariate Bar Legends (continued)
Plate
This discrete covariate bar contains too
many categories to print. You may try
printing in portrait mode.
```
This seems like a feature(limitation) rather than a bug.  We might want to remove this limitation in the future.

**Comment by jmelott** [comment]
As of v 2.23.2, for the legends that can't print properly, the legend is not printed, only the corresponding message.
