### ISSUE TITLE
Save State contains user information

### ISSUE THREAD

**Issue by bmbroom** [MD-Anderson-Bioinformatics/NG-CHM#228]
Save state contains unnecessary details of the user/environment that saved the heat map.

**Comment by jmelott** [comment]
I could use more information on what was in map that is no longer saved and where I would expect to find this information so I'll know what to look for and where to look for it.

**Comment by bmbroom** [comment]
It was included in the HTML that was saved by the package Mary used to create the original save format.

The new save format does not use that package or include a copy of the screen HTML.

The save state information is in the mapConfig.json file, entry panel_layout (if it exists).

**Comment by bmbroom** [comment]
Any user-information: e.g. host names, user name(s), path names.
