### ISSUE TITLE
Limit scope of variables and functions

### ISSUE THREAD

**Issue by bmbroom** [MD-Anderson-Bioinformatics/NG-CHM#232]
Variables and functions assigned to a namespace module, for instance `NgChm.module.variable`, can be accessed or modified _from anywhere_, not just `module`. They are effectively global variables and global functions.  Some modules do this for every non-local variable and function they use.

Since these variables and functions can be used or modified from anywhere, it makes it very hard to understand the impact of possible changes.  You have to scan the entire code base (and that of the builder as well) for every variable/function concerned.

We should take advantage of scopes and IIFEs to limit the scope of variables and functions to the minimum necessary.

**Comment by jmelott** [comment]
@bmbroom  Is this fixed in v2.23.2 to the extent that you want it to be or should we leave this issue open?

**Comment by bmbroom** [comment]
I think it's fixed enough that we can close the issue.
