### ISSUE TITLE
Labels on PDF for detail pane being drawn off bottom of page.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#244]
Open deprez 1000 map or pretty much any one with long column labels.
Save as PDF.
Open PDF and look at column labels on detail map page.

**Comment by bmbroom** [comment]
Font size is selected by the user in the PDF generator dialog.
Amount of space for labels is chosen based on size in the detail pane. (I think the idea is that the proportions of the dendrogram/map/labels in the PDF mirrors that in the viewer panel.)
Neither is adjusted in the case labels don't fit in allocated space.

**Comment by jmelott** [comment]
Still present in version 2.21.2 on 2022 02 11.

**Comment by jmelott** [comment]
Fixed in v2.23.2 build 4.
