### ISSUE TITLE
Selected points in Scatterplot panel restored on map load of saved map.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#273]
To reproduce:
Open a map.
Add a new panel and set to a 3D Scatterplot
Configure Scatterplot such that it is valid.
Select some cells in the detail panel.
(Those points will display as selected in the 3D scatterplot.) 
Save map.
Load saved map.
Though the correct cells are selected in the detail panel, they are not highlighted in the 3D scatterplot.

**Comment by marohrdanz** [comment]
This appears to be addressed by #384 (tested with deprez3000.ngchm in FireFox)
