### ISSUE TITLE
If detail map pane in ribbon mode is zoomed out to full map, then saved, ribbon mode is reset to "Normal" mode on reload.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#313]
To reproduce:
Load a map.
Add pane below default summary and detail panes and set both to map detail pane.
Set one detail pane to vertical ribbon mode and one to horizontal ribbon mode.
Zoom out on all three detail panes until they show the full map in each one.
Save the map.
Load the saved map.
Though all three panes will still be zoomed out to the full map as expected, all three panes will now be in "Normal" mode instead of the two of them being in the ribbon mode they were in when the map was saved.

**Comment by bmbroom** [comment]
The map save state only includes the current view state ('FULL MAP').  Fixing this will require saving at least the previous state as well.

**Comment by bmbroom** [comment]
Before saving, the ribbon mode button is selected, so maybe just saving that will suffice.  I don't know that we want to get into saving the state history as well.

**Comment by jmelott** [comment]
Just saving the state of the ribbon buttons seems like it should be sufficient to me.  If someone zooms back in from full screen, other than the original user who saved the map, no one would have known what the previous state was anyway.  If someone saved the map at full screen, we have to assume there was a reason that was more important than the not-full-screen state anyway.  What will you use as the default not-full-screen selection area to go back to if someone someone zooms out in this case if that isn't saved in the map?
