### ISSUE TITLE
Search Clinical trials link is misconfigured.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#317]
The Search Clinical trials link is in the wrong section /misconfigured.  If multiple genes are selected it fails.  It should be using the only-one-gene type instead of the multiple selected genes type (Which would move it up to the top section of the linkouts).

**Comment by bmbroom** [comment]
I don't think it's "wrong".  It works for one gene but also provides the capability to search for trials that mention multiple genes (e.g. TP53 and EGFR).
However, I will add a single gene version as well.
