### ISSUE TITLE
Exception when loading old map via mapid - Blank detail

### ISSUE THREAD

**Issue by ChrisWakefield** [MD-Anderson-Bioinformatics/NG-CHM#320]
Uncaught TypeError: Cannot convert undefined or null to object - SearchManager.js:100

Object "searchResults" was not fully initialized.  I suspect this was introduced with state save/restore.

**Comment by jmelott** [comment]
Can you provide an example (link to a map or an attached map) where this happens that someone can use to verify the issue exists and later test that it has been fixed?  I'm not seeing it with a map I checked from the TCGA compendium on production currently.

**Comment by ChrisWakefield** [comment]
<supersecret-server>:8188/NGCHM/chm.html?map=568bf58a2128f7cee1698e03a0f43a22b293d483
..i.e. the "Sample NG-CHM" that you see the link to when viewing <any server>:8188

"Stage" appears to be unresponsive at the moment, and I'm working on udev6.

**Comment by ChrisWakefield** [comment]
This was fixed with release 2.22.1 back in May, 2022.
Verify (in 2.22.2) with https://bioinformatics.mdanderson.org/ngchm/chm.html?map=568bf58a2128f7cee1698e03a0f43a22b293d483
