### ISSUE TITLE
Search term not updated for discrete covariates in maps from TCGA compendium

### ISSUE THREAD

**Issue by bmbroom** [MD-Anderson-Bioinformatics/NG-CHM#321]
For a map opened from the TCGA compendium:

Changing the search category to a discrete covariate does not update the search box (dropdown checkboxes for choices).

Doing so on a map loaded from a file in standalone mode works as expected.

**Comment by bmbroom** [comment]
Actually, no search related UI functions work for maps opened from the TCGA compendium.  It's possible it works sometimes, but not for me.

**Comment by jmelott** [comment]
Can you provide some information on how to test this without the latest software being moved to the NGCHM Compendium server?

**Comment by bmbroom** [comment]
Add a map with a discrete covariate bar to your own shaidy server installation and use that.  (Hopefully, bug #369 is fixed.)

**Comment by jmelott** [comment]
Bradley or someone with an existing shaidy server installation will test.
