### ISSUE TITLE
Bug in NGCHM_Widgetizer use of script tag

### ISSUE THREAD

**Issue by ChrisWakefield** [MD-Anderson-Bioinformatics/NG-CHM#324]
This was originally reported as an issue with NGCHM-R package (https://github.com/MD-Anderson-Bioinformatics/NGCHM-R/issues/30)

**Comment by jmelott** [comment]
I verified that the code worked to create a valid HTML and ngchm file following the instructions on https://md-anderson-bioinformatics.github.io/NGCHM-R/articles/create-a-ng-chm.html in the 2.22.2 release.

**Comment by ChrisWakefield** [comment]
Thanks James!  Closing as fixed.

**Comment by marohrdanz** [comment]
Reference info:

- Fixed in 8cf61747e8
- Merged as part of #339
