### ISSUE TITLE
Clicking on gear menu icon while another gear menu open fails

### ISSUE THREAD

**Issue by marohrdanz** [MD-Anderson-Bioinformatics/NG-CHM#325]
If one gear menu is open, clicking on the gear icon in a different panel does nothing and gives a console message error:

```
Uncaught ReferenceError: assignment to undeclared variable item
```

from Linkouts.js line 1760.

This error is NOT present on ngchm.net, which currently has 2.20.1, nor in a locally tested version 2.22.2 (8c228da).

However IS present in c6d1f96.

**Comment by marohrdanz** [comment]
I think this can be resolved by adding a 'let' to 'items' in the for loop. Maybe the declaration of 'item' was removed in some earlier commit.


from **Linkouts.js**:

```js
1758     function removeOpenGearPanels () {
1759       const gears = document.getElementsByClassName('gearPanel');
1760       for (let item of gears) {   /* Added 'let' here */
1761         const paneId = item.id.substring(0,item.id.indexOf("Gear"));
1762         PANE.clearExistingGearDialog(paneId);
1763           } 
1764     }
```

**Comment by bmbroom** [comment]
Line 1760 (without the let) was made in the following commit by Mark back in 2021:

https://github.com/MD-Anderson-Bioinformatics/NG-CHM/commit/2a5c499eee3c1a322530284a0210c28bb88c39ec#diff-a31a1acbd0c55504f4f66e72c257294c20c86be5c4eb0468bd7c279941dea4bd

What causes it to be a problem now is more likely recent changes aimed at more complete usage of strict mode.  (In strict mode this is an error. Previously it would just create/modify a global variable.)

Why don't you submit a patch?
