### ISSUE TITLE
Sometimes GRAB does not give the average of rows/cols

### ISSUE THREAD

**Issue by marohrdanz** [MD-Anderson-Bioinformatics/NG-CHM#329]
Under certain situations (I think mostly when maps are very small) if multiple rows are selected and GRAB is used to collect data in the gear dialog, the values sent to the plugin are NOT the average.

I introduced this bug in 0f954e83a80f6254aa5c73cc442bb395125f5fe0, while adding promises to wait for tiles to load before getting data.

Here is a screenshot displaying the issue:

![Screen Shot 2022-09-07 at 12 51 44 PM](https://user-images.githubusercontent.com/15746330/188947966-a9724c5a-1629-4803-bb2f-11ad2a5fb78d.png)

**Comment by marohrdanz** [comment]
This was addressed in pull request #330 , so marking 'ready for testing'

**Comment by jmelott** [comment]
Can you provide more detailed information on how best to test this?

**Comment by marohrdanz** [comment]
To use the example in the figure: I verified that "Coordinate 2" passed to the plugin was actually the average of 

- 1.138771 and -0.246053 (first column)
- 1.32355713 and 0.02729972 (second column)
- -0.6910582 and 0.4802257 (third column)

Practically speaking: I wrote an R script to generate an NGCHM and calculate simple statistics on the matrix, then manually verified the data passed to the plugin was in agreement with the output of my R script.

We really need more a formalized testing structure :woman_facepalming:

**Comment by jmelott** [comment]
If the map you created is small and you rename it with a .zip extension and attach it to this issue, I can use that to retest.
If you have a listing of what bad values were when it wasn't working and what should be expected and how to find them, that would be helpful.

**Comment by marohrdanz** [comment]
I don't have that exact map. Would any small map do?

**Comment by marohrdanz** [comment]
Here is one that is the same size as the example in the issue.

[small.zip](https://github.com/MD-Anderson-Bioinformatics/NG-CHM/files/10126777/small.zip)

**Comment by jmelott** [comment]
Fixed in version 2.23.1
