### ISSUE TITLE
Update /Downloads version

### ISSUE THREAD

**Issue by marohrdanz** [MD-Anderson-Bioinformatics/NG-CHM#333]
The version available at https://www.ngchm.net/Downloads/ngChmApp.html is still 2.20.1.

**Comment by bmbroom** [comment]
This appears to be at version 2.22.2 now.

**Comment by ChrisWakefield** [comment]
Doesn't "ngchm.net" have its own project?  This should be an issue there, and could really be about ensuring updates to that site.  @jmelott, you added the bug label even though bmbroom stated it was current days prior to that - so I'm not sure what we do with this other than wait for you to mark it tested so we can close it.
