### ISSUE TITLE
Switching between ribbon modes can cause detail maps to be drawn incorrectly.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#355]
![image](https://user-images.githubusercontent.com/7407788/202290052-b6319095-4a8b-481e-8ac1-c034c3b78adf.png)

**Comment by bmbroom** [comment]
How did you get this to happen?

**Comment by jmelott** [comment]
Not sure of exact circumstances not.  Not easily repeatable today though it happened a few times yesterday just by clicking between the two ribbon modes on the rightmost panel.  I'll keep experimenting with it to see if I can come up with something more repeatable.

**Comment by jmelott** [comment]
OK, I just got it to repeat.  I couldn't get it to happen with an original deprez1000 map but I could from a saved version of it. 
Open deprez1000 map and arrange the map like shown in the screenshot.
Save heatmap changes.
Load the saved map, then switch between ribbon modes in the rightmost detail pane.
Here's a copy of the saved map where it happened for me at a lesser degree than with the screenshot.  (Just remove the .zip extension)

[deprez1000 (17).ngchm.zip](https://github.com/MD-Anderson-Bioinformatics/NG-CHM/files/10034887/deprez1000.17.ngchm.zip)

**Comment by bmbroom** [comment]
It took a lot before I could reliably recreate this.  For a long time, I could only reproduce it in the right panel of your saved map just after loading it. 

For the record, I can now reproduce it (in all maps I've tried) as follows:

Position the detail view near the right edge (in normal mode, zoomed in a bit (e.g. so labels show)).
Switch to h ribbon mode.
Zoom out at least once.
Switch to v ribbon mode.

This generates a big gap as in your image above.

The further to the left the initial view, the smaller the gap (eventually no gap).
The more times you zoom out the bigger the gap.

**Comment by bmbroom** [comment]
Also happens on the other axis if you swap all the axes in the above procedure.

Fixed in commit f00176d.
