### ISSUE TITLE
Highlighted Row labels not changing on Detail pane when items selected on 3D or 2D ScatterPlot.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#360]
To reproduce:
Open deprez1000.ngchm.
Make some selections on detail pane.
Zoom to where you can see some of the selected row labels.

Open new pane under Summary pane.
Select new pane to be 3D ScatterPlot.
Accept default settings on Pane Dialog and close dialog.
At this point, 3D Scatterplot will be drawn with current selections.

Click Lasso tool on 3D Scatterplot and select some new points.
At this point, new selected points will be updated on columns on Summary pane, and lines selecting areas in the detail pane grid will be redrawn, highlighted column labels on detail pane will change
Highlighted row labels on detail pane and selected areas on summary pane will not change.

**Comment by bmbroom** [comment]
Which 3D Scatterplot are you using?  I am using the version at https://www.ngchm.net/Plugins/ScatterPlot/index.html. It doesn't have a lasso tool.

Using the 2D scatterplot instead, it appears to be working as intended.  The points in the scatterplot are only from the column axis.  Selecting a new set of points means selecting new columns from in the heat map.  The selected rows should not change.

You can change the "Points Axis" drop down at the top of the gear panel to "row" and it will plot the rows in the heat map as points in the scatterplot.  You will probably need to pick some columns to use as coordinates and the color by scheme.  Selecting points on the scatter plot will then change the selected rows and leave the selected columns unchanged.

**Comment by jmelott** [comment]
In the case of the 3D scatterplot, it's the "Select by rectangle", but same functionality.   You're right though, my mistake.  It's working as expected, I just forgot about the row vs column settings.
