### ISSUE TITLE
Error when clicking "Open gear menu" icon on plugin panel.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#362]
To reproduce:

Open deprez1000.ngchm.
Open browser console.
Switch Summary pane to 2D ScatterPlot, accept defaults, and close dialog.
Click "Open gear menu" in 2D ScatterPlot pane.
Error appears in console:
Linkout.js:2820 Uncaught ReferenceError: debug is not defined
    at icon.onclick (Linkout.js:2820:4)

**Comment by bmbroom** [comment]
Fixed in commit 0230a8a.
