### ISSUE TITLE
Switching primary detail view does not immediately update sub-ribbon mode region on summary view

### ISSUE THREAD

**Issue by bmbroom** [MD-Anderson-Bioinformatics/NG-CHM#368]
When switching the primary detail view to a detail view with a different sub-ribbon mode region, the summary view is not updated immediately.

**Comment by jmelott** [comment]
Can you give more information on how to test this?
What on the summary wasn't updated immediately?

**Comment by bmbroom** [comment]
To test:
- Open a heat map. Open two detail views.
- Switch each detail window into a sub-dendro view (different from the other window).
- Make the secondary detail window primary, while watching the summary view.
- The highlighted region for the subdendro area does not update immediately.
- Move the mouse around over the summary view until it redraws.  The highlighted region will update.

**Comment by jmelott** [comment]
Fixed in version 2.23.1
