### ISSUE TITLE
Compiled server.app cannot load maps from the server

### ISSUE THREAD

**Issue by bmbroom** [MD-Anderson-Bioinformatics/NG-CHM#369]
The compiled server.app issues several error messages and fails to load NGCHMs from the server.  Loading file mode maps works fine.

**Comment by jmelott** [comment]
Can you provide more detailed information on how to test this?

**Comment by bmbroom** [comment]
To test:
- Compile the application.  (I just build the docker container and extract it from there, but you could also run ant directly on the build_ngchmApp.xml file.)
- Copy the compiled server application into the application area of a shaidyserver/nginx system that has at least one map available.  Exactly how to do this depends on how your shaidy/nginx system is configured.
- Open the application from the nginx system above using the ?map=mapid parameter.
