### ISSUE TITLE
Update Action put version number in README of NGCHMSupportFiles

### ISSUE THREAD

**Issue by marohrdanz** [MD-Anderson-Bioinformatics/NG-CHM#370]
We had been using the GitHub action that builds the [NGCHMSupportFiles](https://github.com/MD-Anderson-Bioinformatics/NGCHMSupportFiles) project to update the version number in the DESCRIPTION file to match that of the tag of the NG-CHM release.

However, we are preparing to submit the NGCHMSupportFiles as a CRAN package, and CRAN requires the version number to be bumped with every CRAN submission. So we must change what we have been doing regarding the formal version numbers in the NGCHMSupportFiles R package.

The plan: change the GitHub Action (file: .github/workflows/build-artifacts.yml) to:

- NOT change the version number in the 'Version:' field of the DESCRIPTION file
- Incorporate the NG-CHM tag version number in 1) the README, and 2) the 'Description:' text of the DESCRIPTION file, and have the Action update that

This plan will allow users to easily see which release of the NG-CHM project was used to build the support files, and simultaneously satisfy the CRAN requirements for changing the NGCHMSupportFiles R package version number with every submission.

**Comment by jmelott** [comment]
You opened it.  Feel free to close it if it's no longer needed.

**Comment by marohrdanz** [comment]
Closing because we no longer plan to put this package in CRAN.
