### ISSUE TITLE
Saved Map not reproducing highlighted dendrogram area on Summary map when reloaded.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#372]
To reproduce:
Open map deprez1000.ngchm.
In summary view, click lower part of first split of row dendrogram on left.
The selected portion of the dendrogram on the left side of the map will be highlighted.
Save map.
Load saved map.
Although all the positions are all correct for what is selected, none of the left dendrogram is selected as it was in the map before it was saved.

**Comment by bmbroom** [comment]
We need to discuss.  The highlight on the summary dendrogram has wider issues.

**Comment by jmelott** [comment]
Fixed in v2.23.2 build 4.
