### ISSUE TITLE
Add progress bar/indicator when saving map

### ISSUE THREAD

**Issue by marohrdanz** [MD-Anderson-Bioinformatics/NG-CHM#392]
When saving a .ngchm file for big-ish map (example: 3000 x 3000) the save takes a decent amount of time, with no feedback to the user that something is happening.

Maybe consider adding a progress bar or some indicator that the .ngchm file is being generated.

**Comment by bmbroom** [comment]
Great minds think alike.

The pull request I just submitted does exactly that.

Bradley

**Comment by jmelott** [comment]
Fixed in 2.23.2 build 4.
