### ISSUE TITLE
Datatype class not found for extension 'ngchm'

### ISSUE THREAD

**Issue by abretaud** [MD-Anderson-Bioinformatics/NG-CHM#4]
Hi,
I'm trying to install NG-CHM on our galaxy server, but I get this error:
`Datatype class not found for extension 'ngchm'`

Should I define the datatype manually?

**Comment by mryaninsilico** [comment]
The NGCHM tools will work even though you are getting that error.  Make sure you are logged in when running the NGCHM tool and you should get the NG-CHM visualization icon in the graph menu of the results.

**Comment by abretaud** [comment]
Ah yes thanks, it works, I didn't test it properly
