### ISSUE TITLE
Possible to get zero width selections with shift-dragging

### ISSUE THREAD

**Issue by TELaroche** [MD-Anderson-Bioinformatics/NG-CHM#439]
Reproducible using tcga_rnaseqv2_acc_v2.0_gene_sample map. Shift-dragging vertically will yield a selection with zero width, displaying a blank detail view.
![zerowidth](https://user-images.githubusercontent.com/122411911/222233100-01f83919-0984-4cd2-be6c-0ceed09c1a49.PNG)

**Comment by jmelott** [comment]
Fixed in 2.23.2 build 4
