### ISSUE TITLE
Saving and loading saved map causes last flick layer to be displayed instead of last one displayed.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#451]
To reproduce:
Open deprez1000 map.
Click on flick menu.  
By default it opens to the top layer which is set to "Row Centered".
Save the map.
Open saved map.
Even though no change was made, the map opens in second layer, "Original".

**Comment by bmbroom** [comment]
Flick state (up vs. down) was not actually being saved.

You will need to re-save maps in the fixed version to save the flick state.

**Comment by jmelott** [comment]
Fixed in version 2.23.2 build 7.
