### ISSUE TITLE
PDF creation breaks if DPI too high with unclear message for user about how to fix the problem.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#474]
Creating a PDF from a 2000 x 2000 map at anything larger than 700 dpi breaks process.
User gets error dialog that doesn't explain that they need to lower the DPI:
     Unexpected error detected during PDF generation: Invalid string length.
      Please consider making or contributing to a bug report on our [NG-CHM issues page](https://github.com/MD-Anderson-
      Bioinformatics/NG-CHM/issues?q=is%3Aissue+is%3Aopen+pdf+-label%3Aenhancement).

In developer console the following message appears:
PdfGenerator.js:162 RangeError: Invalid string length
    at t.__addimage__.arrayBufferToBinaryString (addimage.js:766:34)
    at t.processPNG (png_support.js:465:39)
    at Object.P (addimage.js:919:40)
    at t.addImage (addimage.js:855:34)
    at drawSummaryHeatMapPage (PdfGenerator.js:1422:14)
    at PdfGenerator.js:283:3
    at new Promise (<anonymous>)
    at Object.addSummaryPage [as summary] (PdfGenerator.js:282:13)
    at doNextJob (PdfGenerator.js:268:16)

**Comment by jmelott** [comment]
Getting a message as asked, but still getting an error in the console.  Is there some sort of check we can do ahead of time to prevent the error or possibly even give some hint of what size they can use for the map if an error is generated?  Otherwise they just have to manually keep trying smaller DPIs until one works.

For test that generates the error, I used the deprez1000 map and tried to generate a PDF at 1100 or 1200 dpi.

Error:
PdfGenerator.js:162 RangeError: Invalid string length
    at Array.join (<anonymous>)
    at M.y.__private__.buildDocument (jspdf.js:2999:20)
    at M.y.save (jspdf.js:5842:22)
    at PdfGenerator.js:148:14

**Comment by bmbroom** [comment]
The error is being generated deep within the jspdf library.  It also seems to depend on the browser: several map/dpi combos that caused errors in Chrome did not cause errors in Firefox.

For now at least it's not worth the effort to fix.

**Comment by jmelott** [comment]
I'll make a new issue non-show-stopper about the error then and marked this one as passed retest.
