### ISSUE TITLE
Drag-select in detail view causes errors in console and doesn't select if started in either covariate area.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#491]
To reproduce:
Open Developer console.
Open any map with covariates.
In detail panel Click mouse in covariate area and drag across main map area.
(Someone trying to select the top left cell could easily do this accidentally.)
No area will be selected and multiple instances of the following error will appear in the console.
uginInstanceManager.js:175 Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at PIM.postSelectionToPlugins (PluginInstanceManager.js:175:25)
    at SRCH.updateLinkoutSelections (SearchManager.js:121:6)
    at DEV.handleSelectDrag (DetailHeatMapEvent.js:754:14)
    at DEV.handleMouseMove (DetailHeatMapEvent.js:672:7)
PIM.postSelectionToPlugins @ PluginInstanceManager.js:175
SRCH.updateLinkoutSelections @ SearchManager.js:121
DEV.handleSelectDrag @ DetailHeatMapEvent.js:754
DEV.handleMouseMove @ DetailHeatMapEvent.js:672

**Comment by bmbroom** [comment]
I cannot replicate.

**Comment by jmelott** [comment]
Try with shift-drag specifically.  In detail panel, start in column covariates and drag onto main matrix area.

**Comment by jmelott** [comment]
With additional testing, I determined that it only seems to happen if the detail map is positioned near the top of the map. It may also depend on where you start in the column covariates vs how many rows down you've moved the detail view down from the top.  
Easily seen if you load the deprez1000 map with the detail view at the top of the map. Start the shift-drag at the topmost covariate and drag into the main map matrix.
