### ISSUE TITLE
Where is custom-plugins.js

### ISSUE THREAD

**Issue by lh12565** [MD-Anderson-Bioinformatics/NG-CHM#496]
Hi, I want to embed Next-Generation Clustered Heat Maps to my website. I followed the https://www.ngchm.net/post/how-to-embed-next-generation-clustered-heat-maps-v2/ said. I didn't find the "custom-plugins.js" file, so I couldn't use linkout function. I try to replace the custom-plugins.js to the custom.js in this repository, but there is an error as below:
```
embedNGCHM('#NGCHM', 'fileName', 'tt.ngchm',{customJS: 'custom.js'})
```
```
Uncaught TypeError: Cannot read properties of undefined (reading 'bio.pubmed')
```
Please help me solve this problem.
Thanks!

**Comment by ChrisWakefield** [comment]
Hello,
custom-plugins.js is a file you would create to add your own capabilities.  The file custom.js already exists at WebContent/javascript/custom/custom.js, and that is already being loaded / executed prior to what is passed as "customJS".

Please view the file custom.js (https://github.com/MD-Anderson-Bioinformatics/NG-CHM/blob/main/NGCHM/WebContent/javascript/custom/custom.js) to see how the function linkouts.addPlugin() is used.
In the example NGCHM labeled as Figure 1, the NGCHM is embedded in an iframe, and the functions to add linkouts is seen at "window.frames[0].linkouts".

Please include the version number of the release as shown under the "NgChm Help" menu item if you need further assistance.  You may also want to share your custom linkouts javascript.

I hope this helps!

**Comment by ChrisWakefield** [comment]
@bmbroom @marohrdanz @jmelott
Is it all right to just close this issue from early May?

**Comment by bmbroom** [comment]
I think so.
