### ISSUE TITLE
Error generated when opening new panel with map containing ScatterPlot and some other features.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#499]
Originally found in GUI Builder 2.21.3 w/ NG-CHM 2.23.5-build-13
Didn't happen just creating a map with a scatterplot covariate with sample matrix.

To reproduce:
Open the attached map in the GUI builder (Probably have to go through viewer and select to upload all to builder.)
[matrix_11_2000_2000_samples_samples (2).ngchm.zip](https://github.com/MD-Anderson-Bioinformatics/NG-CHM_GUI_BUILDER/files/11500082/matrix_11_2000_2000_samples_samples.2.ngchm.zip)
Open developer console.

Change summary panel to detail panel.

Attempt to open new panel below original detail panel on left.
Following error message will appear in console.
ngchmWidget-min.js?v…d45ae5da48dc8ba:408 Uncaught RangeError: Invalid array length
at a.buildScatterBarPlotMatrix (ngchmWidget-min.js?v…e5da48dc8ba:408:185)
at n.drawScatterBarPlotColClassBar (ngchmWidget-min.js?v…e5da48dc8ba:501:203)
at ngchmWidget-min.js?v…ae5da48dc8ba:500:95
at Array.forEach ()
at n.detailDrawColClassBars (ngchmWidget-min.js?v…e5da48dc8ba:499:247)
at n.getDetailHeatMap (ngchmWidget-min.js?v…e5da48dc8ba:457:438)
at n.drawDetailHeatMap (ngchmWidget-min.js?v…e5da48dc8ba:451:433)
at ngchmWidget-min.js?v…ae5da48dc8ba:448:99

Bradley was able to reproduce in the viewer outside the builder.
•	Add panel below detail panel and make the top panel somewhat small
•	Add another panel below the top panel
•	Move the new divider up and down

**Comment by bmbroom** [comment]
Actually, you just need to:

- create one additional panel
- move the divider up to make the top panel very small
- move the divider up and down until the bug triggers

It happens when panel tries to render a zero-height covariate bar.

**Comment by jmelott** [comment]
Retesting again, I could not get the above error to happen again.
