### ISSUE TITLE
Drag of "prefs panel" doesn't work

### ISSUE THREAD

**Issue by ChrisWakefield** [MD-Anderson-Bioinformatics/NG-CHM#94]
It looks like the current code never worked.  When NGCHM is embedded in HTML file, clicking on the header of the prefs panel causes it to jump out of view, forcing the user to reopen the panel to get it back to its original position.  Repeatable in both Chrome and Firefox.
The code is in NgChm.UTIL.dragElement().
This also affects pdfPrefs, "msgBox", and "linkBox", whatever those are.

**Comment by mstucky** [comment]
Hi Chris,

It looks like the drag element works for the standard viewer in web mode, gui builder and using the stand-alone viewer.  I also gave it a run in some of my fairly basic stand-alone examples and it seemed to work.  

Is this an issue that occurs only in Tod's implementation of stand-alone?  I cannot work on this but perhaps the e.clientX and e.clientY values referenced in the dragElement function are returning unexpected positional values in whatever implementation is not working correctly.

BTW: PdfPrefs - refers to the popup when you try to create a pdf from the hamburger (which can be dragged with the dragElement logic); msgBox - any message box (e.g. Save dialog); linkBox - is the linkout popup that is opened from the hamburger.

**Comment by ChrisWakefield** [comment]
Mark!  It's good to hear from you!
It's not Tod (this time!), but yes, I suspect it's only when the embedded html is not at the top of it's frame, whether it's an iframe or a toplevel window.  So it works for all the cases you mentioned, but not when offsets are non-zero.  I think I'll have it sorted by next release.

**Comment by marohrdanz** [comment]
Is it enough to test this issue by embedding the NGCHM Viewer in an iframe in a normal HTML page and verifying the drag of these elements works? If so (I did that test just now), this issue appears resolved by e2f9e7bca8795ad4efd1b676ea674f5d4ff8480d.

**Comment by marohrdanz** [comment]
I verified dragging the preferences / user help / pdf preferences also work as desired if I build ngchmEmbed-min.js and ngchmWidget-min.js from the latest in 'mary-bug-fixes' (9858324, which includes the above-mentioned e2f9e7b) and embed into an HTML page following the guidelines in https://github.com/MD-Anderson-Bioinformatics/NG-CHM/blob/master/NGCHM/Documentation/NGCHM_Embed-Reference.docx
